### ISSUE TITLE
Agree on username and survey naming schema

### ISSUE THREAD

**Issue by empicano** [fast-survey/backend#33]
I will name each collection containing data of a specific survey like this: `username.surveyid`. MongoDB has some [naming restrictions for collections](https://docs.mongodb.com/manual/reference/limits/#Restriction-on-Collection-Names), thus we would need to need to restrict the username and survey to a specific schema.

@dostuffthatmatters, what do you think about allowing only lowercase ascii, numbers and the hyphen for usernames and survey ids? We could restrict length to be between 2 and 20 or something similar.

Also, I would reserve every username containing "fastsurvey", and due to MongoDB internals the "system" username.

**Comment by dostuffthatmatters** [comment]
I would actually forbid everything where `<username>.<surveyname>` contains both `fast` and `survey`. That is a very easy check and there is still some room for possible survey names 😉

**Comment by empicano** [comment]
On GitHub I can create a repository called "github". I don't think there's any danger of spoofing in naming surveys after fastsurvey. Other than that I don't see any reason to unnecessarily constrict naming. Do you have a specific usecase for it?

**Comment by empicano** [comment]
To summarize, so we can close this afterwards:

Naming schema for user names and survey names:
- lowercase ascii letters `[a-z]`
- numbers `[0-9]`
- hyphen `-`
- user name length of 1-20 (?)
- survey name length of 1-20 (?)
- no combination of `fast` and `survey` in user name (and survey name?)

**Comment by dostuffthatmatters** [comment]
I want to encourage people to use meaningful survey names, not just `fastsurvey.io/<username>/fastsurvey` this is one tiny step towards more descriptive routes :)

Why is it so relevant to give admins this freedom? ^^

I would also like to give them a hint (not an error just a hint) when they are using names like `survey-01` or `survey1` or `surveyA`. This happens purely on the frontend though.

**Comment by empicano** [comment]
Not super relevant per se, but I want to understand the reason behind something before implementing it.

I quite like this idea of encouraging descriptive naming. How about putting this all in one basket: we restrict the usernames like we talked about, while encouraging, but not enforcing, non-descriptive survey names (survey1, survey2, etc. including fastsurvey) on the frontend?

**Comment by dostuffthatmatters** [comment]
Ok sounds good 👌🏻

The first lawsuit because of something that happened in our name is on you hahaha 😅

**Comment by empicano** [comment]
Haha, great deal :smile:  

To summarize:

Naming schema for user names and survey names:
- lowercase ascii letters `[a-z]`
- numbers `[0-9]`
- hyphen `-`
- user name length of 1-20
- survey name length of 1-20
- encourage descriptive survey naming to avoid names like survey1, survey2, etc.
- prohibit any combination of `fast` and `survey` in user name

**Comment by dostuffthatmatters** [comment]
One thing: Should we allow usernames and survey names from length `1`?

**Comment by empicano** [comment]
I don't have any preference over that. For me, only some maximum limit would be important because MongoDB has maximum limits for collection names (which are more generous than 20 characters though, but that felt like a good limit). Simply edit the summary if you feel that it should be different.
