### ISSUE TITLE
(When) Should admins be able modify existing surveys?

### ISSUE THREAD

**Issue by empicano** [fast-survey/backend#36]
Seems like a cool feature at first glance, though it arises some problems:
- If admins were able to change a survey while its open for submissions, submission contents would be inconsistent. This would for example make aggregating the results in the end very complicated, and furthermore only partially complete.
- An option would be to let the admin change the survey when it has not yet been opened. This seems possible, I would need to make sure that there are no race conditions when the new configuration comes in at the last second the survey is still closed, and the first submission comes in at the next second.
- Another option could be to only let the admin change non-structural (e.g. descriptions) things during the time the survey is open. I would be against that, as one could theoretically change the sense of questions, thus destroying the validity of the results.

**Comment by dostuffthatmatters** [comment]
Allowing that before a survey has been opened (with a buffer) seems good, however **we will have to implements server-to-server messaging before allowing that**.

What many content-related sites do, is to have **two states "draft" and "published"**. We could create every survey as a draft by default and add a "publish" button. As soon as the admin clicks "publish", the backend models will be populated, the frontend routes work and the survey should not be changed anymore.

**When trying to modify the survey after publishing**, e could give admins two options (just two buttons with explanation):
1. Modify existing survey and flush all submissions (show submision count)
2. Duplicate this survey = Create a copy of this survey in draft mode

**Comment by empicano** [comment]
I'll find a good option to make the changing reliable via some lock. I prefer that to a buffer, as a buffer won't necessarily eliminate all race conditions. As long as we stay on one instance I think I can implement it without messaging. With multiple instances you're right though, but that's for later on.

I like the idea of survey states. I can come up with 5 states:
- **draft**: not yet open for the public, no start and end date specified, lets the admin store configurations
- **scheduled**: not yet open for the public, but start and end date specified, will open and close automatically
- **published**: currently running
- **closed**: after the survey closed, survey can still be reopened, submissions can be downloaded
- **archived**: something like over two weeks after the end date, submissions are deleted

Having the option to manually open and close the survey would be cool! The easiest way to implement this is probably by letting the frontend simply "schedule" the start/end date to right now.

To modify it after publishing, I'd only use the second way: close the current one and provide an option to duplicate survey configuration (I would always make that option available). Less complicated than two ways, for the admin and for us :smile:

**Comment by dostuffthatmatters** [comment]
Do we event need the states scheduled and closed? I mean we do include the start and end date in the config, so they define, when submitting is possible. The only state we need is actually draft/published/archived right?

Yes, only offering the first method would be very convenient for now. Should we then rename the old identifier or the new one or let the admin pick?

**Comment by empicano** [comment]
In terms of the database we don't need to save any of these states, they can all be infered from the values in start/end/archive. The states I listed were more meant to be something like logical states that a survey can be in, to make it easier to reason about them. Following this we could e.g. use these states in explanations in the docs or show them alongside the surveys on the dashboard, so the admin can quickly see what's up.

Maybe if the original is `my-survey` then the copy is simply named `my-survey-copy`? Renaming will be possible afterwards anyways. I think the copy function would be cool to have anyways, to not have to remake the whole survey e.g. when one wants to retake it with other people after a year.

**Comment by dostuffthatmatters** [comment]
Ok, great! Sounds good!

About **copying**: I definitely want to add that! I also imagined copying single fields :) super simple from a JSON config perspective and also rather simple in the frontend since the config page is directly built from the json :D

**Comment by empicano** [comment]
Good idea! Ok, so editing only when not yet published, otherwise we'll provide an easy way to copy. I'll close this then :relaxed:

**Comment by dostuffthatmatters** [comment]
![giphy](https://user-images.githubusercontent.com/29046316/84997204-8bd85f00-b14e-11ea-9db3-79cb26887be4.gif)
